spring.application.name=orchestrator
server.port=8080

services.order.url=http://localhost:8081
services.payment.url=http://localhost:8082
services.inventory.url=http://localhost:8083

saga.step-delay-ms=800

logging.pattern.console=%d{HH:mm:ss.SSS} [${spring.application.name}] [%X{sagaId}] %-5level %msg%n